// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ocr.proto
// Protobuf C++ Version: 6.33.1

#include "ocr.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ocr {

inline constexpr ProcessImageResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        processing_time_ms_{::int64_t{0}},
        ok_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ProcessImageResponse::ProcessImageResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ProcessImageResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProcessImageResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessImageResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessImageResponseDefaultTypeInternal() {}
  union {
    ProcessImageResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessImageResponseDefaultTypeInternal _ProcessImageResponse_default_instance_;

inline constexpr ProcessImageRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        client_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        batch_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        image_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        lang_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ProcessImageRequest::ProcessImageRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ProcessImageRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProcessImageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessImageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessImageRequestDefaultTypeInternal() {}
  union {
    ProcessImageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessImageRequestDefaultTypeInternal _ProcessImageRequest_default_instance_;
}  // namespace ocr
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_ocr_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_ocr_2eproto = nullptr;
const ::uint32_t
    TableStruct_ocr_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageRequest, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageRequest, _impl_.client_id_),
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageRequest, _impl_.batch_id_),
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageRequest, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageRequest, _impl_.image_),
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageRequest, _impl_.lang_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageResponse, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageResponse, _impl_.ok_),
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageResponse, _impl_.text_),
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageResponse, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::ocr::ProcessImageResponse, _impl_.processing_time_ms_),
        3,
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::ocr::ProcessImageRequest)},
        {13, sizeof(::ocr::ProcessImageResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::ocr::_ProcessImageRequest_default_instance_._instance,
    &::ocr::_ProcessImageResponse_default_instance_._instance,
};
const char descriptor_table_protodef_ocr_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tocr.proto\022\003ocr\"i\n\023ProcessImageRequest\022"
    "\021\n\tclient_id\030\001 \001(\t\022\020\n\010batch_id\030\002 \001(\t\022\020\n\010"
    "filename\030\003 \001(\t\022\r\n\005image\030\004 \001(\014\022\014\n\004lang\030\005 "
    "\001(\t\"]\n\024ProcessImageResponse\022\n\n\002ok\030\001 \001(\010\022"
    "\014\n\004text\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022\032\n\022proces"
    "sing_time_ms\030\004 \001(\0032Q\n\nOCRService\022C\n\014Proc"
    "essImage\022\030.ocr.ProcessImageRequest\032\031.ocr"
    ".ProcessImageResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_ocr_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ocr_2eproto = {
    false,
    false,
    309,
    descriptor_table_protodef_ocr_2eproto,
    "ocr.proto",
    &descriptor_table_ocr_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_ocr_2eproto::offsets,
    file_level_enum_descriptors_ocr_2eproto,
    file_level_service_descriptors_ocr_2eproto,
};
namespace ocr {
// ===================================================================

class ProcessImageRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ProcessImageRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_._has_bits_);
};

ProcessImageRequest::ProcessImageRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessImageRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ocr.ProcessImageRequest)
}
PROTOBUF_NDEBUG_INLINE ProcessImageRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ocr::ProcessImageRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        client_id_(arena, from.client_id_),
        batch_id_(arena, from.batch_id_),
        filename_(arena, from.filename_),
        image_(arena, from.image_),
        lang_(arena, from.lang_) {}

ProcessImageRequest::ProcessImageRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ProcessImageRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessImageRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProcessImageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ocr.ProcessImageRequest)
}
PROTOBUF_NDEBUG_INLINE ProcessImageRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        client_id_(arena),
        batch_id_(arena),
        filename_(arena),
        image_(arena),
        lang_(arena) {}

inline void ProcessImageRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ProcessImageRequest::~ProcessImageRequest() {
  // @@protoc_insertion_point(destructor:ocr.ProcessImageRequest)
  SharedDtor(*this);
}
inline void ProcessImageRequest::SharedDtor(MessageLite& self) {
  ProcessImageRequest& this_ = static_cast<ProcessImageRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.client_id_.Destroy();
  this_._impl_.batch_id_.Destroy();
  this_._impl_.filename_.Destroy();
  this_._impl_.image_.Destroy();
  this_._impl_.lang_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ProcessImageRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ProcessImageRequest(arena);
}
constexpr auto ProcessImageRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ProcessImageRequest),
                                            alignof(ProcessImageRequest));
}
constexpr auto ProcessImageRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ProcessImageRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ProcessImageRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ProcessImageRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ProcessImageRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ProcessImageRequest>(), &ProcessImageRequest::ByteSizeLong,
              &ProcessImageRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_._cached_size_),
          false,
      },
      &ProcessImageRequest::kDescriptorMethods,
      &descriptor_table_ocr_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ProcessImageRequest_class_data_ =
        ProcessImageRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ProcessImageRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ProcessImageRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ProcessImageRequest_class_data_.tc_table);
  return ProcessImageRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 61, 2>
ProcessImageRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ProcessImageRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ocr::ProcessImageRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string client_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.client_id_)}},
    // string batch_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.batch_id_)}},
    // string filename = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.filename_)}},
    // bytes image = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 3, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.image_)}},
    // string lang = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 4, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.lang_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string client_id = 1;
    {PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.client_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string batch_id = 2;
    {PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.batch_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string filename = 3;
    {PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.filename_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes image = 4;
    {PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.image_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // string lang = 5;
    {PROTOBUF_FIELD_OFFSET(ProcessImageRequest, _impl_.lang_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\11\10\10\0\4\0\0"
    "ocr.ProcessImageRequest"
    "client_id"
    "batch_id"
    "filename"
    "lang"
  }},
};
PROTOBUF_NOINLINE void ProcessImageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ocr.ProcessImageRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.client_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.batch_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.image_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.lang_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ProcessImageRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ProcessImageRequest& this_ = static_cast<const ProcessImageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ProcessImageRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ProcessImageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ocr.ProcessImageRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string client_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_client_id().empty()) {
      const ::std::string& _s = this_._internal_client_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ProcessImageRequest.client_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string batch_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_batch_id().empty()) {
      const ::std::string& _s = this_._internal_batch_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ProcessImageRequest.batch_id");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string filename = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_filename().empty()) {
      const ::std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ProcessImageRequest.filename");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // bytes image = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_image().empty()) {
      const ::std::string& _s = this_._internal_image();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  // string lang = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_lang().empty()) {
      const ::std::string& _s = this_._internal_lang();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ProcessImageRequest.lang");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ocr.ProcessImageRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ProcessImageRequest::ByteSizeLong(const MessageLite& base) {
  const ProcessImageRequest& this_ = static_cast<const ProcessImageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ProcessImageRequest::ByteSizeLong() const {
  const ProcessImageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ocr.ProcessImageRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string client_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_client_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_client_id());
      }
    }
    // string batch_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_batch_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_batch_id());
      }
    }
    // string filename = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // bytes image = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_image().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_image());
      }
    }
    // string lang = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_lang().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_lang());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ProcessImageRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ProcessImageRequest*>(&to_msg);
  auto& from = static_cast<const ProcessImageRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:ocr.ProcessImageRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_client_id().empty()) {
        _this->_internal_set_client_id(from._internal_client_id());
      } else {
        if (_this->_impl_.client_id_.IsDefault()) {
          _this->_internal_set_client_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_batch_id().empty()) {
        _this->_internal_set_batch_id(from._internal_batch_id());
      } else {
        if (_this->_impl_.batch_id_.IsDefault()) {
          _this->_internal_set_batch_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_image().empty()) {
        _this->_internal_set_image(from._internal_image());
      } else {
        if (_this->_impl_.image_.IsDefault()) {
          _this->_internal_set_image("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_lang().empty()) {
        _this->_internal_set_lang(from._internal_lang());
      } else {
        if (_this->_impl_.lang_.IsDefault()) {
          _this->_internal_set_lang("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ProcessImageRequest::CopyFrom(const ProcessImageRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ocr.ProcessImageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProcessImageRequest::InternalSwap(ProcessImageRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_id_, &other->_impl_.client_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.batch_id_, &other->_impl_.batch_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_, &other->_impl_.image_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.lang_, &other->_impl_.lang_, arena);
}

::google::protobuf::Metadata ProcessImageRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProcessImageResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ProcessImageResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_._has_bits_);
};

ProcessImageResponse::ProcessImageResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessImageResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ocr.ProcessImageResponse)
}
PROTOBUF_NDEBUG_INLINE ProcessImageResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ocr::ProcessImageResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        text_(arena, from.text_),
        message_(arena, from.message_) {}

ProcessImageResponse::ProcessImageResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ProcessImageResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessImageResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProcessImageResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, processing_time_ms_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, processing_time_ms_),
           offsetof(Impl_, ok_) -
               offsetof(Impl_, processing_time_ms_) +
               sizeof(Impl_::ok_));

  // @@protoc_insertion_point(copy_constructor:ocr.ProcessImageResponse)
}
PROTOBUF_NDEBUG_INLINE ProcessImageResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        text_(arena),
        message_(arena) {}

inline void ProcessImageResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, processing_time_ms_),
           0,
           offsetof(Impl_, ok_) -
               offsetof(Impl_, processing_time_ms_) +
               sizeof(Impl_::ok_));
}
ProcessImageResponse::~ProcessImageResponse() {
  // @@protoc_insertion_point(destructor:ocr.ProcessImageResponse)
  SharedDtor(*this);
}
inline void ProcessImageResponse::SharedDtor(MessageLite& self) {
  ProcessImageResponse& this_ = static_cast<ProcessImageResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.text_.Destroy();
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ProcessImageResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ProcessImageResponse(arena);
}
constexpr auto ProcessImageResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ProcessImageResponse),
                                            alignof(ProcessImageResponse));
}
constexpr auto ProcessImageResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ProcessImageResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ProcessImageResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ProcessImageResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ProcessImageResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ProcessImageResponse>(), &ProcessImageResponse::ByteSizeLong,
              &ProcessImageResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_._cached_size_),
          false,
      },
      &ProcessImageResponse::kDescriptorMethods,
      &descriptor_table_ocr_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ProcessImageResponse_class_data_ =
        ProcessImageResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ProcessImageResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ProcessImageResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ProcessImageResponse_class_data_.tc_table);
  return ProcessImageResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 44, 2>
ProcessImageResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ProcessImageResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ocr::ProcessImageResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 processing_time_ms = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ProcessImageResponse, _impl_.processing_time_ms_), 2>(),
     {32, 2, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.processing_time_ms_)}},
    // bool ok = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ProcessImageResponse, _impl_.ok_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.ok_)}},
    // string text = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.text_)}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool ok = 1;
    {PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.ok_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string text = 2;
    {PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.text_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.message_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 processing_time_ms = 4;
    {PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.processing_time_ms_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\30\0\4\7\0\0\0\0"
    "ocr.ProcessImageResponse"
    "text"
    "message"
  }},
};
PROTOBUF_NOINLINE void ProcessImageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ocr.ProcessImageResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.text_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.processing_time_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.ok_) -
        reinterpret_cast<char*>(&_impl_.processing_time_ms_)) + sizeof(_impl_.ok_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ProcessImageResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ProcessImageResponse& this_ = static_cast<const ProcessImageResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ProcessImageResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ProcessImageResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ocr.ProcessImageResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool ok = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_ok() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_ok(), target);
    }
  }

  // string text = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_text().empty()) {
      const ::std::string& _s = this_._internal_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ProcessImageResponse.text");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string message = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ProcessImageResponse.message");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // int64 processing_time_ms = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_processing_time_ms() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_processing_time_ms(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ocr.ProcessImageResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ProcessImageResponse::ByteSizeLong(const MessageLite& base) {
  const ProcessImageResponse& this_ = static_cast<const ProcessImageResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ProcessImageResponse::ByteSizeLong() const {
  const ProcessImageResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ocr.ProcessImageResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string text = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_text().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_text());
      }
    }
    // string message = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // int64 processing_time_ms = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_processing_time_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_processing_time_ms());
      }
    }
    // bool ok = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_ok() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ProcessImageResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ProcessImageResponse*>(&to_msg);
  auto& from = static_cast<const ProcessImageResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:ocr.ProcessImageResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_text().empty()) {
        _this->_internal_set_text(from._internal_text());
      } else {
        if (_this->_impl_.text_.IsDefault()) {
          _this->_internal_set_text("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_processing_time_ms() != 0) {
        _this->_impl_.processing_time_ms_ = from._impl_.processing_time_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_ok() != 0) {
        _this->_impl_.ok_ = from._impl_.ok_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ProcessImageResponse::CopyFrom(const ProcessImageResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ocr.ProcessImageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProcessImageResponse::InternalSwap(ProcessImageResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.ok_)
      + sizeof(ProcessImageResponse::_impl_.ok_)
      - PROTOBUF_FIELD_OFFSET(ProcessImageResponse, _impl_.processing_time_ms_)>(
          reinterpret_cast<char*>(&_impl_.processing_time_ms_),
          reinterpret_cast<char*>(&other->_impl_.processing_time_ms_));
}

::google::protobuf::Metadata ProcessImageResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ocr
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ocr_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
